---
title: "ENV 790.30 - Time Series Analysis for Energy Data | Spring 2023"
subtitle: "Assignment 1 - Due date 01/24/23"
<<<<<<< HEAD:Assignments/TonyJiang_TSA_A01_Sp23.Rmd
author: "Tony Jiang"
=======
author: "Luana"
>>>>>>> 7ab51001fb26c7f98e21f745884a2fb9b769989d:Assignments/TSA_A01_Sp22.Rmd
output: pdf_document
geometry: margin=2.54cm
---

## Directions
ss
Before making any edits to this file, please rename it such that it includes your first and last name (e.g., "LuanaLima_TSA_A01_Sp23.Rmd")

Once you have this renamed file open in RStudio, the first thing you will do is replace "Student Name" on line 3 with your name. 
Then you will start working through the assignment by  **creating code and output** that answer each question. Be sure to use this assignment document. Your report should contain the answer to each question and any plots/tables you obtained (when applicable).

When you have completed the assignment, **Knit** the text and code into a single PDF file.  Submit this pdf using Sakai. 

## Questions

Q1. What are your previous experiences with time series analysis, R, and Git? 

<<<<<<< HEAD:Assignments/TonyJiang_TSA_A01_Sp23.Rmd
> Answer: I have learned time series analysis in my Stats class at Duke. But the class only covered basic knowledge of time series analysis. 
          I self-learned R a little bit during this winter break. I know some basic syntax, funtions, and packages, like ggplot2, for..in.... But I have short previous coding exprience in my undergrad (JAVA). So, i am relatively familiar with coding in general and R. 
          I have no experience in Git. So, this is may be the biggest challenge for me at the beginning of this semester.
=======
> Answer: None
>>>>>>> 7ab51001fb26c7f98e21f745884a2fb9b769989d:Assignments/TSA_A01_Sp22.Rmd


Q2. (Only if you choose to use git) Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file as instructed on the recorded video "Getting started with Git and Github". 

> Answer: Link to my forked course repository: https://github.com/CastDown/TimeSeriesAnalysis_Sp23


Q3. For this part we just want to see the path to your R project. No need to do anything. The output will be automatically generated once you knit you file. 

> Answer: This is my working directory:/Users/jiangliwei/Documents/Semester 4/Time Series Anaysis for Energy Data/Forked Repository/Forked TSA Spring 2023
          This is the local path to my R project. Hopefully, this is correct! 

```{r}
getwd()
````


